# Generated by Django 3.2 on 2021-12-13 18:49

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='data',
            field=models.FileField(upload_to=task.models.GenerateAttachmentFilePath()),
        ),
    ]
