# Generated by Django 3.2 on 2021-12-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_attachment_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='task_status',
            new_name='status',
        ),
    ]
