# Generated by Django 4.0 on 2021-12-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_status',
            field=models.IntegerField(choices=[(0, 'ONLINE'), (1, 'OFFLINE'), (2, 'DONOTDISTURB')], default=0),
        ),
    ]
