# Generated by Django 4.0 on 2021-12-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_status',
            field=models.IntegerField(choices=[(0, 'ONLINE'), (1, 'OFFLINE'), (2, 'DONOTDISTURB')], default=1),
        ),
    ]
